apiVersion: v1
kind: ServiceAccount
metadata:
  name: recipe-box-app
  namespace: recipe-box
  labels:
    app.kubernetes.io/name: recipe-box
    app.kubernetes.io/component: api
automountServiceAccountToken: false
